In [1]:
import numpy as np

In [2]:

# 1. Δημιουργία ενός NumPy Array (Πίνακα) με τιμές σπιτιών
prices = np.array([120000, 250000, 85000, 420000, 190000])

# 2. Vectorization: Θέλουμε να αυξήσουμε ΟΛΕΣ τις τιμές κατά 10%
# Στην απλή Python θα θέλαμε loop. Στο NumPy γίνεται σε 1 γραμμή!
inflation_prices = prices * 1.10

print("Αρχικές τιμές:")
print(prices)
print("\nΤιμές με πληθωρισμό 10%:")
print(inflation_prices)

Αρχικές τιμές:
[120000 250000  85000 420000 190000]

Τιμές με πληθωρισμό 10%:
[132000. 275000.  93500. 462000. 209000.]


In [3]:
import numpy as np

# 1. Δημιουργία ενός NumPy Array (Πίνακα) με τιμές σπιτιών
prices = np.array([120000, 250000, 85000, 420000, 190000])

# 2. Vectorization: Θέλουμε να αυξήσουμε ΟΛΕΣ τις τιμές κατά 10%
# Στην απλή Python θα θέλαμε loop. Στο NumPy γίνεται σε 1 γραμμή!
inflation_prices = prices * 1.10

print("Αρχικές τιμές:")
print(prices)
print("\nΤιμές με πληθωρισμό 10%:")
print(inflation_prices)

Αρχικές τιμές:
[120000 250000  85000 420000 190000]

Τιμές με πληθωρισμό 10%:
[132000. 275000.  93500. 462000. 209000.]


In [4]:
# Δημιουργούμε ένα "φίλτρο" (True/False)
filter_expensive = prices > 200000

print("Το φίλτρο μας:")
print(filter_expensive) # Θα σου βγάλει [False, True, False, True, False]

# Εφαρμόζουμε το φίλτρο στο αρχικό array για να πάρουμε ΜΟΝΟ τα ακριβά σπίτια
expensive_houses = prices[filter_expensive]

print("\nΣπίτια άνω των 200.000€:")
print(expensive_houses)

Το φίλτρο μας:
[False  True False  True False]

Σπίτια άνω των 200.000€:
[250000 420000]
